Repository Nookipedia/nookipedia-api, pull requests merged in 2021-04, with the labels that each got.

#45 New Horizons Item endpoints
  app.py
Labels: new endpoint

#47 New Horizones events endpoint
  .gitattributes
  app.py
  requirements.txt
  static/doc.json
  static/doc.yaml
Labels: new endpoint

#42 Caching with memcached and adding MediaWiki auth
  README.md
  app.py
  config.ini
  requirements.txt
Labels: enhancement

#52 Some Bug fixes
  app.py
  requirements.txt
Labels: bug

#53 Documented objects for NH items
  static/doc.yaml
Labels: documentation

#49 Boilerplate Cleanup
  app.py
Labels: enhancement

#56 Doc updates for NH event + item endpoints
  static/doc.html
  static/doc.json
  static/doc.yaml
Labels: documentation
